### PR TITLE
Upgrade to play 2.5.4, play-slick 2.0.0

### PR DESCRIPTION
**Pull request by jbdeboer**
Upgrades the dependencies to the current versions.

In Play 2.5, `Play.current` is deprecated, so I applied the recommended "legacy" fix.

Also, a few minor style changes.

### CODE REVIEW

**Comment by pedrorijo91** [comment]
Hi @jbdeboer 

I really appreciate your intentions on updating the example to Play 2.5.4 (the current latest release). 

But to be honest, this tutorial was aiming more to Scala starters, and one of the reasons why I did this example was because I could only found tutorials with a lot of boilerplate. And I do think DI will make readers focus on what they shouldn't be worried about when trying to learn how to use Slick with Play.

Still, I think I will just create a branch for Play 2.5.x and merge your PR into that branch, as soon as I have some time.

Once again, thanks, and feel free to contribute if you find something that you feel it could be improved :)

**Comment by pedrorijo91** [comment]
@jbdeboer sorry for taking so much time. Can i ask you to edit the PR to the branch [play2.5](https://github.com/pedrorijo91/play-slick3-steps/tree/play2.5) ?

**Comment by jbdeboer** [comment]
I don't have the bandwidth right now.

**Comment by pedrorijo91** [comment]
no problem, as soon as you can just ping me :)

**Comment by pedrorijo91** [comment]
Closing, as replicated by #4 since the author hadn't the availability to change the destiny branch.

Thanks a lot for the contribution @jbdeboer !

**Pull request closed without merging**
